name: Watch Roblox user (only on status change)

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (adjust if you want)
  workflow_dispatch:         # allow manual run

permissions:
  contents: write            # needed to commit the status file

env:
  USER_ID: "7807146843"      # <— the Roblox user to watch
  PLAYER_NAME: "Test"      # <— display name in the embed
  PROFILE_URL: "https://www.roblox.com/users/7807146843/profile"

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure jq exists
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Load last known status (if any)
        id: last
        shell: bash
        run: |
          FILE=".status/${USER_ID}.json"
          if [ -f "$FILE" ]; then
            LAST_STATUS=$(jq -r '.status' "$FILE")
          else
            LAST_STATUS="unknown"
          fi
          echo "last_status=$LAST_STATUS" >> $GITHUB_OUTPUT

      - name: Fetch current presence from Roblox
        id: now
        run: |
          DATA=$(curl -s -X POST https://presence.roblox.com/v1/presence/users \
            -H "Content-Type: application/json" \
            -d "{\"userIds\":[${USER_ID}]}")

          echo "$DATA" > data.json
          STATUS=$(jq -r '.userPresences[0].userPresenceType' data.json)
          PLACE_ID=$(jq -r '.userPresences[0].placeId // empty' data.json)
          UNIVERSE_ID=$(jq -r '.userPresences[0].universeId // empty' data.json)

          # Map 0=OFFLINE, 1=ONLINE, 2=IN_GAME, 3=IN_STUDIO (rare), 4=??? (reserved)
          case "$STATUS" in
            0) STATUS_NAME="OFFLINE" ;;
            1) STATUS_NAME="ONLINE" ;;
            2) STATUS_NAME="IN_GAME" ;;
            3) STATUS_NAME="IN_STUDIO" ;;
            *) STATUS_NAME="UNKNOWN" ;;
          esac

          echo "status_raw=$STATUS" >> $GITHUB_OUTPUT
          echo "status_name=$STATUS_NAME" >> $GITHUB_OUTPUT
          echo "place_id=$PLACE_ID" >> $GITHUB_OUTPUT
          echo "universe_id=$UNIVERSE_ID" >> $GITHUB_OUTPUT

      - name: Decide if status changed
        id: decide
        run: |
          if [ "${{ steps.now.outputs.status_name }}" != "${{ steps.last.outputs.last_status }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Post Discord embed (only if changed)
        if: steps.decide.outputs.changed == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PLAYER_NAME: ${{ env.PLAYER_NAME }}
          PROFILE_URL: ${{ env.PROFILE_URL }}
          STATUS_NAME: ${{ steps.now.outputs.status_name }}
          PLACE_ID: ${{ steps.now.outputs.place_id }}
          STATUS_RAW: ${{ steps.now.outputs.status_raw }}
        run: |
          # Build buttons dynamically: Join only if IN_GAME (status_raw==2 and place_id is present)
          if [ "$STATUS_RAW" = "2" ] && [ -n "$PLACE_ID" ] && [ "$PLACE_ID" != "null" ]; then
            JOIN_BUTTON='{
              "type": 2, "style": 5, "label": "Join Game",
              "url": "https://www.roblox.com/games/'"$PLACE_ID"'"
            }'
          else
            JOIN_BUTTON=""
          fi

          # Components array (buttons)
          if [ -n "$JOIN_BUTTON" ]; then
            COMPONENTS='{
              "type": 1,
              "components": [
                '"$JOIN_BUTTON"',
                { "type": 2, "style": 5, "label": "View Profile", "url": "'"$PROFILE_URL"'" }
              ]
            }'
          else
            COMPONENTS='{
              "type": 1,
              "components": [
                { "type": 2, "style": 5, "label": "View Profile", "url": "'"$PROFILE_URL"'" }
              ]
            }'
          fi

          # Embed color: green for ONLINE/IN_GAME, red for OFFLINE, gray otherwise
          case "$STATUS_NAME" in
            "IN_GAME"|"ONLINE") COLOR=3066993 ;;   # green
            "OFFLINE")          COLOR=15158332 ;;  # red
            *)                  COLOR=9807270 ;;   # gray
          esac

          cat > payload.json <<EOF
{
  "embeds": [
    {
      "title": "${PLAYER_NAME} is now ${STATUS_NAME}",
      "description": "Status changed. Click below for profile${JOIN_BUTTON:+ or to join.}",
      "color": ${COLOR},
      "url": "${PROFILE_URL}"
    }
  ],
  "components": [ ${COMPONENTS} ]
}
EOF

          curl -s -H "Content-Type: application/json" -X POST -d @payload.json "$DISCORD_WEBHOOK" -o /dev/null

      - name: Update saved status (only if changed)
        if: steps.decide.outputs.changed == 'true'
        run: |
          mkdir -p .status
          printf '{ "status": "%s", "ts": "%s", "placeId": "%s" }\n' \
            "${{ steps.now.outputs.status_name }}" \
            "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            "${{ steps.now.outputs.place_id }}" > ".status/${USER_ID}.json"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .status/${USER_ID}.json
          git commit -m "chore: update ${USER_ID} status -> ${{ steps.now.outputs.status_name }}" || echo "No changes to commit"
          git push
